### ISSUE TITLE
tempalte not working for Zabbix >3.x

### ISSUE THREAD

**Issue by chuegel** [begood-technology/ZABBIX#3]
Hi,

unfortunately the template doesn´t work for Zabbix version > 3.x
Would it be possible to update the template? Thank you.

**Comment by ScriptByScript** [comment]
According to Dave Jacobs (https://share.zabbix.com/network_devices/loadmaster-template) - the problem is with two item descriptions. Open the XML file, search for 8bit .. and replace the x character that comes before the 8bit with an actual x. For some reason the character isn't a true x. Once you do that, it should import fine.
